In [2]:
import pandas as pd

df = pd.read_csv('../data/raw/thrift_data.csv')
df.head()

,Unnamed: 0,item_name,brand,condition,source,cost,selling_price,discount,final_price,profit,quantity,date,days_to_sell,customer_type,payment_method,category
0,0,T-Shirt,Nike,New,Donation,8.92,23.41,4.83,18.58,9.66,1,2026-03-12 21:35:36.579343,20,Returning,Mobile Money,Topwear
1,1,Sneakers,Zara,New,Donation,7.55,20.69,2.83,17.86,10.31,2,2026-02-08 21:35:36.579407,5,New,Cash,Footwear
2,2,Hoodie,Zara,Good,Donation,13.02,32.61,0.85,31.76,18.74,4,2026-03-22 21:35:36.579438,20,Returning,Mobile Money,Topwear
3,3,Jeans,Adidas,New,Market,12.61,21.54,3.20,18.34,5.73,2,2026-03-24 21:35:36.579461,2,New,Mobile Money,Bottomwear
4,4,Sneakers,H&M,New,Market,10.76,21.52,1.24,20.28,9.52,5,2026-03-29 21:35:36.579484,5,New,Mobile Money,Footwear

In [3]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      200 non-null    int64
 1   item_name       200 non-null    str
 2   brand           200 non-null    str
 3   condition       200 non-null    str
 4   source          200 non-null    str
 5   cost            200 non-null    float64
 6   selling_price   200 non-null    float64
 7   discount        200 non-null    float64
 8   final_price     200 non-null    float64
 9   profit          200 non-null    float64
 10  quantity        200 non-null    int64
 11  date            200 non-null    str
 12  days_to_sell    200 non-null    int64
 13  customer_type   200 non-null    str
 14  payment_method  200 non-null    str
 15  category        200 non-null    str
dtypes: float64(5), int64(3), str(8)
memory usage: 25.1 KB

,Unnamed: 0,cost,selling_price,discount,final_price,profit,quantity,days_to_sell
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,99.500000,17.906250,39.815700,2.589800,37.225900,19.319650,2.915000,15.290000
std,57.879185,7.136563,17.483681,1.478977,17.713678,11.983536,1.370095,8.260574
min,0.000000,5.020000,9.400000,0.000000,6.640000,0.690000,1.000000,1.000000
25%,49.750000,12.097500,24.387500,1.362500,22.047500,9.025000,2.000000,8.000000
50%,99.500000,18.105000,39.900000,2.705000,38.245000,17.870000,3.000000,16.000000
75%,149.250000,24.097500,50.625000,3.760000,47.917500,26.470000,4.000000,22.000000
max,199.000000,29.880000,83.860000,4.980000,81.530000,52.700000,5.000000,30.000000

In [4]:
# total revnue per row
df['revenue'] = df['final_price'] * df['quantity']

# total cost
df['total_cost'] = df['cost'] * df['quantity']

# total profit
df['total_profit'] = df['profit'] * df['quantity']

In [5]:
# Core Business questions:
# 1) Which category makes the most profit?
df.groupby('category')['total_profit'].sum().sort_values(ascending=False)

# 2) Which items sell fastest?
df.groupby('item_name')['days_to_sell'].mean().sort_values()

# 3) Which source is most profitable?
df.groupby('source')['total_profit'].sum().sort_values(ascending=False)

# 4) Which brand performs best?
df.groupby('brand')['total_profit'].sum().sort_values(ascending=False)

# 5) What customer behavior is observed?
df.groupby('customer_type')['total_profit'].sum()
# Are returning customers worth more?

# 6) What is the customer payment behaviour?
df.groupby("payment_method")["total_profit"].sum()

df.head()

,Unnamed: 0,item_name,brand,condition,source,cost,selling_price,discount,final_price,profit,quantity,date,days_to_sell,customer_type,payment_method,category,revenue,total_cost,total_profit
0,0,T-Shirt,Nike,New,Donation,8.92,23.41,4.83,18.58,9.66,1,2026-03-12 21:35:36.579343,20,Returning,Mobile Money,Topwear,18.58,8.92,9.66
1,1,Sneakers,Zara,New,Donation,7.55,20.69,2.83,17.86,10.31,2,2026-02-08 21:35:36.579407,5,New,Cash,Footwear,35.72,15.10,20.62
2,2,Hoodie,Zara,Good,Donation,13.02,32.61,0.85,31.76,18.74,4,2026-03-22 21:35:36.579438,20,Returning,Mobile Money,Topwear,127.04,52.08,74.96
3,3,Jeans,Adidas,New,Market,12.61,21.54,3.20,18.34,5.73,2,2026-03-24 21:35:36.579461,2,New,Mobile Money,Bottomwear,36.68,25.22,11.46
4,4,Sneakers,H&M,New,Market,10.76,21.52,1.24,20.28,9.52,5,2026-03-29 21:35:36.579484,5,New,Mobile Money,Footwear,101.40,53.80,47.60

In [8]:
df[df['days_to_sell'] > 20]

,Unnamed: 0,item_name,brand,condition,source,cost,selling_price,discount,final_price,profit,quantity,date,days_to_sell,customer_type,payment_method,category,revenue,total_cost,total_profit
7,7,Jeans,Zara,Good,Market,11.36,28.10,3.60,24.50,13.14,1,2026-03-13 21:35:36.579554,26,New,Cash,Bottomwear,24.50,11.36,13.14
11,11,Jeans,Adidas,Good,Market,16.77,37.73,1.64,36.09,19.32,5,2026-02-01 21:35:36.579646,30,Returning,Mobile Money,Bottomwear,180.45,83.85,96.60
13,13,Hoodie,Nike,Worn,Supplier,7.38,17.38,4.21,13.17,5.79,2,2026-02-11 21:35:36.579689,22,New,Mobile Money,Topwear,26.34,14.76,11.58
17,17,Jacket,Zara,Worn,Donation,25.31,64.90,3.76,61.14,35.83,2,2026-02-07 21:35:36.579782,22,Returning,Mobile Money,Outerwear,122.28,50.62,71.66
20,20,Hoodie,H&M,Good,Supplier,28.00,59.72,0.51,59.21,31.21,4,2026-02-08 21:35:36.579847,23,New,Cash,Topwear,236.84,112.00,124.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
184,184,Hoodie,Puma,Good,Market,8.26,23.41,3.64,19.77,11.51,4,2026-03-09 21:35:36.582836,29,Returning,Mobile Money,Topwear,79.08,33.04,46.04
188,188,Hoodie,Nike,New,Market,5.28,10.63,3.81,6.82,1.54,1,2026-03-21 21:35:36.582900,22,Returning,Mobile Money,Topwear,6.82,5.28,1.54
191,191,Hoodie,Zara,Good,Donation,25.44,47.49,3.70,43.79,18.35,5,2026-02-04 21:35:36.582950,24,Returning,Cash,Topwear,218.95,127.20,91.75
195,195,Jeans,Zara,Worn,Market,26.62,71.69,4.88,66.81,40.19,3,2026-03-16 21:35:36.582992,24,Returning,Cash,Bottomwear,200.43,79.86,120.57
197,197,Jacket,Nike,Good,Supplier,13.83,29.42,2.33,27.09,13.26,4,2026-03-29 21:35:36.583016,24,Returning,Mobile Money,Outerwear,108.36,55.32,53.04

In [ ]:
df[df["profit"] < 5]

,Unnamed: 0,item_name,brand,condition,source,cost,selling_price,discount,final_price,profit,quantity,date,days_to_sell,customer_type,payment_method,category,revenue,total_cost,total_profit
8,8,Jacket,Puma,New,Market,9.97,16.26,2.85,13.41,3.44,3,2026-02-02 21:35:36.579578,19,New,Cash,Outerwear,40.23,29.91,10.32
30,30,Jeans,Puma,Good,Market,5.52,11.97,4.68,7.29,1.77,3,2026-03-16 21:35:36.580061,22,Returning,Cash,Bottomwear,21.87,16.56,5.31
37,37,Sneakers,Adidas,Good,Supplier,5.95,11.33,4.69,6.64,0.69,5,2026-03-02 21:35:36.580243,15,Returning,Cash,Footwear,33.20,29.75,3.45
54,54,Jeans,H&M,New,Supplier,10.97,17.75,3.29,14.46,3.49,1,2026-03-03 21:35:36.580639,28,New,Mobile Money,Bottomwear,14.46,10.97,3.49
65,65,Jacket,H&M,New,Market,5.83,11.97,4.20,7.77,1.94,2,2026-02-11 21:35:36.580887,17,Returning,Mobile Money,Outerwear,15.54,11.66,3.88
72,72,Jeans,Nike,New,Market,7.90,12.64,3.03,9.61,1.71,1,2026-02-23 21:35:36.581041,12,New,Cash,Bottomwear,9.61,7.90,1.71
74,74,Jacket,Adidas,Good,Market,12.06,21.54,4.86,16.68,4.62,2,2026-03-18 21:35:36.581086,29,Returning,Mobile Money,Outerwear,33.36,24.12,9.24
76,76,Sneakers,Zara,Good,Market,7.78,11.79,2.43,9.36,1.58,4,2026-02-26 21:35:36.581129,12,New,Mobile Money,Footwear,37.44,31.12,6.32
85,85,T-Shirt,Adidas,New,Market,5.89,11.87,3.76,8.11,2.22,5,2026-03-24 21:35:36.581325,8,New,Cash,Topwear,40.55,29.45,11.10
88,88,Jacket,Adidas,Good,Donation,8.33,12.90,2.75,10.15,1.82,4,2026-02-09 21:35:36.581390,7,Returning,Mobile Money,Outerwear,40.60,33.32,7.28
121,121,Jeans,Zara,Worn,Supplier,9.64,18.17,4.14,14.03,4.39,2,2026-02-27 21:35:36.582101,16,Returning,Mobile Money,Bottomwear,28.06,19.28,8.78
129,129,Hoodie,Adidas,Worn,Supplier,5.60,9.40,2.22,7.18,1.58,2,2026-02-15 21:35:36.582199,6,New,Cash,Topwear,14.36,11.20,3.16
137,137,Jeans,Adidas,Good,Supplier,12.42,18.97,4.74,14.23,1.81,1,2026-02-05 21:35:36.582302,3,Returning,Cash,Bottomwear,14.23,12.42,1.81
148,148,Sneakers,Zara,Worn,Supplier,7.90,16.64,4.77,11.87,3.97,4,2026-03-28 21:35:36.582419,30,Returning,Mobile Money,Footwear,47.48,31.60,15.88
174,174,Jeans,Adidas,Worn,Market,13.14,20.25,2.54,17.71,4.57,4,2026-03-28 21:35:36.582699,16,Returning,Mobile Money,Bottomwear,70.84,52.56,18.28
186,186,Jeans,Nike,New,Supplier,6.07,13.37,2.57,10.80,4.73,1,2026-03-21 21:35:36.582868,1,New,Mobile Money,Bottomwear,10.80,6.07,4.73
188,188,Hoodie,Nike,New,Market,5.28,10.63,3.81,6.82,1.54,1,2026-03-21 21:35:36.582900,22,Returning,Mobile Money,Topwear,6.82,5.28,1.54
189,189,Jacket,H&M,Good,Supplier,5.02,9.45,2.23,7.22,2.20,2,2026-02-19 21:35:36.582917,3,Returning,Mobile Money,Outerwear,14.44,10.04,4.40