In [3]:
import pandas as pd

df = pd.read_csv('../data/raw/thrift_data.csv')
df.head()

,Unnamed: 0,item_name,brand,condition,source,cost,selling_price,discount,final_price,profit,quantity,date,days_to_sell,customer_type,payment_method,category
0,0,T-Shirt,Nike,New,Donation,8.92,23.41,4.83,18.58,9.66,1,2026-03-12 21:35:36.579343,20,Returning,Mobile Money,Topwear
1,1,Sneakers,Zara,New,Donation,7.55,20.69,2.83,17.86,10.31,2,2026-02-08 21:35:36.579407,5,New,Cash,Footwear
2,2,Hoodie,Zara,Good,Donation,13.02,32.61,0.85,31.76,18.74,4,2026-03-22 21:35:36.579438,20,Returning,Mobile Money,Topwear
3,3,Jeans,Adidas,New,Market,12.61,21.54,3.20,18.34,5.73,2,2026-03-24 21:35:36.579461,2,New,Mobile Money,Bottomwear
4,4,Sneakers,H&M,New,Market,10.76,21.52,1.24,20.28,9.52,5,2026-03-29 21:35:36.579484,5,New,Mobile Money,Footwear

In [4]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      200 non-null    int64
 1   item_name       200 non-null    str
 2   brand           200 non-null    str
 3   condition       200 non-null    str
 4   source          200 non-null    str
 5   cost            200 non-null    float64
 6   selling_price   200 non-null    float64
 7   discount        200 non-null    float64
 8   final_price     200 non-null    float64
 9   profit          200 non-null    float64
 10  quantity        200 non-null    int64
 11  date            200 non-null    str
 12  days_to_sell    200 non-null    int64
 13  customer_type   200 non-null    str
 14  payment_method  200 non-null    str
 15  category        200 non-null    str
dtypes: float64(5), int64(3), str(8)
memory usage: 25.1 KB

,Unnamed: 0,cost,selling_price,discount,final_price,profit,quantity,days_to_sell
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,99.500000,17.906250,39.815700,2.589800,37.225900,19.319650,2.915000,15.290000
std,57.879185,7.136563,17.483681,1.478977,17.713678,11.983536,1.370095,8.260574
min,0.000000,5.020000,9.400000,0.000000,6.640000,0.690000,1.000000,1.000000
25%,49.750000,12.097500,24.387500,1.362500,22.047500,9.025000,2.000000,8.000000
50%,99.500000,18.105000,39.900000,2.705000,38.245000,17.870000,3.000000,16.000000
75%,149.250000,24.097500,50.625000,3.760000,47.917500,26.470000,4.000000,22.000000
max,199.000000,29.880000,83.860000,4.980000,81.530000,52.700000,5.000000,30.000000