In [5]:
import pandas as pd

df = pd.read_csv('../data/raw/thrift_data.csv')
df.head()

AttributeError: partially initialized module 'pandas' from 'c:\Users\Admin\AppData\Local\Programs\Python\Python314\Lib\site-packages\pandas\__init__.py' has no attribute '_pandas_datetime_CAPI' (most likely due to a circular import)

In [ ]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      200 non-null    int64
 1   item_name       200 non-null    str
 2   brand           200 non-null    str
 3   item_condition  200 non-null    str
 4   source          200 non-null    str
 5   cost            200 non-null    float64
 6   selling_price   200 non-null    float64
 7   discount        200 non-null    float64
 8   final_price     200 non-null    float64
 9   profit          200 non-null    float64
 10  quantity        200 non-null    int64
 11  date            200 non-null    str
 12  days_to_sell    200 non-null    int64
 13  customer_type   200 non-null    str
 14  payment_method  200 non-null    str
 15  category        200 non-null    str
dtypes: float64(5), int64(3), str(8)
memory usage: 25.1 KB

,Unnamed: 0,cost,selling_price,discount,final_price,profit,quantity,days_to_sell
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,99.500000,17.417650,39.497750,2.318500,37.179250,19.761600,2.910000,15.435000
std,57.879185,7.296168,17.779167,1.447085,17.834181,11.816902,1.334468,9.015106
min,0.000000,5.090000,8.090000,0.070000,7.540000,1.370000,1.000000,1.000000
25%,49.750000,11.007500,25.332500,1.022500,22.135000,10.505000,2.000000,8.000000
50%,99.500000,17.220000,37.200000,2.250000,34.830000,18.145000,3.000000,15.000000
75%,149.250000,24.070000,52.740000,3.492500,50.767500,28.180000,4.000000,24.000000
max,199.000000,29.940000,84.900000,4.990000,84.030000,55.720000,5.000000,30.000000

In [ ]:
# total revnue per row
df['revenue'] = df['final_price'] * df['quantity']

# total cost
df['total_cost'] = df['cost'] * df['quantity']

# total profit
df['total_profit'] = df['profit'] * df['quantity']

In [ ]:
# Core Business questions:
# 1) Which category makes the most profit?
df.groupby('category')['total_profit'].sum().sort_values(ascending=False)

# 2) Which items sell fastest?
df.groupby('item_name')['days_to_sell'].mean().sort_values()

# 3) Which source is most profitable?
df.groupby('source')['total_profit'].sum().sort_values(ascending=False)

# 4) Which brand performs best?
df.groupby('brand')['total_profit'].sum().sort_values(ascending=False)

# 5) What customer behavior is observed?
df.groupby('customer_type')['total_profit'].sum()
# Are returning customers worth more?

# 6) What is the customer payment behaviour?
df.groupby("payment_method")["total_profit"].sum()

df.head()

,Unnamed: 0,item_name,brand,item_condition,source,cost,selling_price,discount,final_price,profit,quantity,date,days_to_sell,customer_type,payment_method,category,revenue,total_cost,total_profit
0,0,Sneakers,Nike,Good,Supplier,26.87,40.47,2.88,37.59,10.72,4,2026-03-09 13:52:38.130835,17,Returning,Cash,Footwear,150.36,107.48,42.88
1,1,T-Shirt,Nike,Worn,Donation,6.06,11.51,1.50,10.01,3.95,4,2026-04-02 13:52:38.130893,11,Returning,Mobile Money,Topwear,40.04,24.24,15.80
2,2,Jeans,H&M,New,Supplier,16.01,37.68,1.16,36.52,20.51,3,2026-02-21 13:52:38.130920,3,Returning,Mobile Money,Bottomwear,109.56,48.03,61.53
3,3,Hoodie,Zara,Worn,Supplier,5.10,8.09,0.55,7.54,2.44,4,2026-03-10 13:52:38.130945,26,Returning,Mobile Money,Topwear,30.16,20.40,9.76
4,4,Hoodie,H&M,Good,Market,10.21,16.25,0.68,15.57,5.36,1,2026-03-13 13:52:38.131000,11,Returning,Mobile Money,Topwear,15.57,10.21,5.36

In [ ]:
df[df['days_to_sell'] > 20]

,Unnamed: 0,item_name,brand,item_condition,source,cost,selling_price,discount,final_price,profit,quantity,date,days_to_sell,customer_type,payment_method,category,revenue,total_cost,total_profit
3,3,Hoodie,Zara,Worn,Supplier,5.10,8.09,0.55,7.54,2.44,4,2026-03-10 13:52:38.130945,26,Returning,Mobile Money,Topwear,30.16,20.40,9.76
7,7,Jacket,Puma,Worn,Supplier,17.76,44.78,0.29,44.49,26.73,2,2026-03-26 13:52:38.131064,25,New,Cash,Outerwear,88.98,35.52,53.46
10,10,T-Shirt,Nike,New,Supplier,17.21,28.49,3.88,24.61,7.40,5,2026-02-14 13:52:38.131140,25,New,Cash,Topwear,123.05,86.05,37.00
12,12,Jacket,Nike,Worn,Market,22.35,56.85,2.57,54.28,31.93,1,2026-03-20 13:52:38.131185,24,New,Mobile Money,Outerwear,54.28,22.35,31.93
14,14,Hoodie,Adidas,Good,Market,26.84,63.26,4.05,59.21,32.37,3,2026-03-31 13:52:38.131231,30,New,Cash,Topwear,177.63,80.52,97.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,183,Hoodie,Nike,New,Market,14.54,33.71,1.30,32.41,17.87,1,2026-02-17 13:52:38.135093,27,New,Mobile Money,Topwear,32.41,14.54,17.87
185,185,T-Shirt,Adidas,Worn,Donation,11.85,33.06,0.26,32.80,20.95,2,2026-02-09 13:52:38.135130,26,New,Mobile Money,Topwear,65.60,23.70,41.90
186,186,Sneakers,H&M,Good,Supplier,16.42,43.67,0.90,42.77,26.35,1,2026-03-01 13:52:38.135147,27,New,Cash,Footwear,42.77,16.42,26.35
190,190,Jacket,Nike,Good,Donation,24.85,57.51,3.18,54.33,29.48,3,2026-03-21 13:52:38.135216,26,Returning,Cash,Outerwear,162.99,74.55,88.44
196,196,Jacket,Nike,Worn,Donation,9.97,21.12,4.22,16.90,6.93,2,2026-03-20 13:52:38.135430,21,New,Mobile Money,Outerwear,33.80,19.94,13.86

In [ ]:
df[df["profit"] < 5]

,Unnamed: 0,item_name,brand,item_condition,source,cost,selling_price,discount,final_price,profit,quantity,date,days_to_sell,customer_type,payment_method,category,revenue,total_cost,total_profit
1,1,T-Shirt,Nike,Worn,Donation,6.06,11.51,1.50,10.01,3.95,4,2026-04-02 13:52:38.130893,11,Returning,Mobile Money,Topwear,40.04,24.24,15.80
3,3,Hoodie,Zara,Worn,Supplier,5.10,8.09,0.55,7.54,2.44,4,2026-03-10 13:52:38.130945,26,Returning,Mobile Money,Topwear,30.16,20.40,9.76
9,9,Sneakers,Zara,New,Market,10.16,15.59,2.14,13.45,3.29,5,2026-04-05 13:52:38.131106,13,New,Mobile Money,Footwear,67.25,50.80,16.45
11,11,Hoodie,Adidas,Worn,Market,12.08,19.23,3.49,15.74,3.66,4,2026-03-24 13:52:38.131162,2,New,Mobile Money,Topwear,62.96,48.32,14.64
13,13,Jacket,Puma,Good,Supplier,14.28,21.46,3.24,18.22,3.94,3,2026-04-06 13:52:38.131209,4,Returning,Cash,Outerwear,54.66,42.84,11.82
29,29,Jacket,Nike,Worn,Donation,5.25,12.82,3.50,9.32,4.07,3,2026-02-22 13:52:38.131583,24,Returning,Cash,Outerwear,27.96,15.75,12.21
58,58,Jacket,Adidas,New,Donation,9.20,14.14,1.67,12.47,3.27,1,2026-02-27 13:52:38.132234,1,New,Cash,Outerwear,12.47,9.20,3.27
61,61,Jeans,Zara,New,Donation,5.87,11.32,2.77,8.55,2.68,2,2026-03-06 13:52:38.132297,14,New,Cash,Bottomwear,17.10,11.74,5.36
77,77,Jeans,Zara,New,Market,10.49,16.43,3.78,12.65,2.16,3,2026-02-09 13:52:38.132638,23,Returning,Mobile Money,Bottomwear,37.95,31.47,6.48
94,94,Jeans,H&M,New,Market,6.33,9.88,2.18,7.70,1.37,3,2026-03-07 13:52:38.133226,5,Returning,Cash,Bottomwear,23.10,18.99,4.11
100,100,T-Shirt,Puma,Good,Donation,7.84,16.45,4.85,11.60,3.76,4,2026-03-21 13:52:38.133359,25,New,Cash,Topwear,46.40,31.36,15.04
119,119,Sneakers,H&M,Good,Donation,5.22,12.93,4.73,8.20,2.98,3,2026-02-23 13:52:38.133741,20,Returning,Cash,Footwear,24.60,15.66,8.94
129,129,Jeans,Nike,Worn,Donation,5.09,12.28,2.66,9.62,4.53,1,2026-02-21 13:52:38.133981,10,New,Mobile Money,Bottomwear,9.62,5.09,4.53
153,153,Hoodie,Puma,Worn,Market,5.19,11.03,3.17,7.86,2.67,3,2026-02-14 13:52:38.134432,30,Returning,Mobile Money,Topwear,23.58,15.57,8.01
164,164,Jacket,Zara,Good,Supplier,8.62,15.24,2.92,12.32,3.70,4,2026-03-06 13:52:38.134656,5,New,Cash,Outerwear,49.28,34.48,14.80
166,166,Hoodie,Adidas,Good,Supplier,5.53,10.79,0.77,10.02,4.49,2,2026-03-25 13:52:38.134693,28,Returning,Mobile Money,Topwear,20.04,11.06,8.98
168,168,Jacket,Zara,New,Supplier,7.96,12.46,2.44,10.02,2.06,2,2026-02-06 13:52:38.134728,25,New,Mobile Money,Outerwear,20.04,15.92,4.12

In [ ]:
df[df['revnenue']]